version: '3.8'
name: sqa
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: water_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  database:
